language: python
python:
  - '3.5'
# command to install dependencies
install: "make"
# command to run tests
script:
  - |
    make init
    make html
    make github

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $GIT_USERNAME
  - git config --local user.email $GIT_EMAIL 

deploy:
  provider: pages
  api_key: $GITHUB_ACCESS
  file_glob: true
  file: output/*
  skip_cleanup: true
    on:
    branch: master
