language: python

services:
  - docker

python:
  - '3.5'
# command to install dependencies
install: "make"
# command to run tests
script:
  - |
    make init
    make html

before_install:
  - docker build -t kreeher/teal-deer .