language: python
python:
  - '3.8'
# command to install dependencies
install: "make"
# command to run tests
script:
  - |
    make init
    make publish
#    make github

deploy:
  provider: pages
  github_token: $GITHUB_ACCESS
  target_branch: gh-pages
  local_dir: output
  skip_cleanup: true
  on:
    branch: master